import { Injectable } from '@nestjs/common';
import OpenAI from 'openai';

@Injectable()
export class ToolCallingService {
  constructor(private readonly openai: OpenAI) {}

  async toolCalling(sign: string): Promise<string> {
    // 1. Define a list of callable tools for the model
    const tools: OpenAI.Responses.Tool[] = [
      {
        type: 'function',
        name: 'get_horoscope',
        description: "Get today's horoscope for an astrological sign.",
        strict: true,
        parameters: {
          type: 'object',
          properties: {
            sign: {
              type: 'string',
              description: 'An astrological sign like Taurus or Aquarius',
            },
          },
          required: ['sign'],
          additionalProperties: false,
        },
      },
    ];

    // Function that is provided access to the model as a tool
    function getHoroscope(sign: string) {
      return sign + ' Next Tuesday you will befriend a baby otter.';
    }

    // Create a running input list we will add to over time
    const input: OpenAI.Responses.ResponseInputItem[] = [
      { role: 'user', content: `What is my horoscope? I am an ${sign}.` },
    ];

    // 2. Prompt the model with tools defined
    let response = await this.openai.responses.create({
      model: 'gpt-4o',
      tools,
      input,
    });

    // Add the model's output (including function_call items) to the input history
    input.push(...response.output);

    response.output.forEach((item) => {
      if (item.type === 'function_call') {
        if (item.name === 'get_horoscope') {
          // 3. Execute the function logic for get_horoscope
          const args = JSON.parse(item.arguments) as { sign: string };
          const horoscope = getHoroscope(args.sign);

          // 4. Provide function call results to the model
          input.push({
            type: 'function_call_output',
            call_id: item.call_id,
            output: JSON.stringify({ horoscope }),
          });
        }
      }
    });

    console.log('Final input:');
    console.log(JSON.stringify(input, null, 2));

    response = await this.openai.responses.create({
      model: 'gpt-4o',
      instructions: 'Respond only with a horoscope generated by a tool.',
      tools,
      input,
    });

    // 5. The model should be able to give a response!
    console.log('Final output:');
    console.log(JSON.stringify(response.output, null, 2));
    return JSON.stringify(response.output, null, 2);
  }
}
